---
title: "check"
output: html_document
date: "2025-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(car)
 data1 <- read.csv("www/data/kidney_disease.csv")
  data2 <- read.csv("www/data/Chronic_Kidney_Disease.csv")
  
  # Data cleaning and preparation for data1
  colnames(data1) <- c('id', 'age', 'blood_pressure', 'specific_gravity', 'albumin', 'sugar', 'red_blood_cells', 'pus_cell',
                       'pus_cell_clumps', 'bacteria', 'blood_glucose_random', 'blood_urea', 'serum_creatinine', 'sodium',
                       'potassium', 'haemoglobin', 'packed_cell_volume', 'white_blood_cell_count', 'red_blood_cell_count',
                       'hypertension', 'diabetes_mellitus', 'coronary_artery_disease', 'appetite', 'peda_edema',
                       'anaemia', 'class')
  
  # Clean data
  data1$coronary_artery_disease <- trimws(data1$coronary_artery_disease)
  data1$hypertension <- trimws(data1$hypertension)
  data1$diabetes_mellitus <- trimws(data1$diabetes_mellitus)
  data1$coronary_artery_disease[data1$coronary_artery_disease == ""] <- NA
  data1$hypertension[data1$hypertension == ""] <- NA
  
  # Filter out rows with NA values
  data1 <- filter(data1, !is.na(coronary_artery_disease) & !is.na(serum_creatinine) & !is.na(albumin))
  
  data1$coronary_artery_disease_numerical <- ifelse(data1$coronary_artery_disease == "yes", 1, 0)
  data1$hypertension_numerical <- ifelse(data1$hypertension == "yes", 1, 0)
  data1$diabetes_mellitus_numerical <- ifelse(data1$diabetes_mellitus == "yes", 1, 0)
  
  # Data preparation for data2
  data2$BMI_category <- cut(data2$BMI,
                            breaks = c(-Inf, 18.5, 24.9, 29.9, Inf),
                            labels = c("Underweight", "Normal", "Overweight", "Obese"))
  
  # Convert the UrinaryTractInfections column into a factor with custom labels
  data2$UrinaryTractInfections_Status <- factor(data2$UrinaryTractInfections, labels = c("No Infection", "Yes Infection"))
  
  # Convert Smoking to factor for better plotting
  data2$Smoking_Status <- factor(data2$Smoking, levels = c(0, 1), labels = c("Non-Smoker", "Smoker"))
```

# Test Chi-Square Assumptions

```{r}
table_data_1 <- table(data1$coronary_artery_disease_numerical, data1$hypertension_numerical)
table_data_2 <- table(data1$coronary_artery_disease_numerical, data1$diabetes_mellitus_numerical)
chi_result_1 <- chisq.test(table_data_1)
chi_result_2 <- chisq.test(table_data_2)
```

## Normality - Do not think this is needed
```{r}
# check Normality
shapiro.test(data1$coronary_artery_disease_numerical)
shapiro.test(data1$hypertension_numerical)
shapiro.test(data1$diabetes_mellitus_numerical)
```

## Homogeneity of Variancey - Do not think this is needed
```{r}
leveneTest(data1$serum_creatinine, data1$coronary_artery_disease)
```

## Expected > 5
```{r}
chi_result_1$expected > 5
chi_result_2$expected > 5
```

```{r}
str(data1)
dim(data1)
dim(data2)
```

